spring.application.name=franchise-api
spring.data.mongodb.uri=mongodb+srv://franchiseUser:eMLG613CYRdQKtan@franchise-api.szexlgq.mongodb.net/franchise_db?appName=franchise-api
spring.mongodb.uri=mongodb+srv://franchiseUser:eMLG613CYRdQKtan@franchise-api.szexlgq.mongodb.net/franchise_db?appName=franchise-api